# Generated by Django 3.0.1 on 2021-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210107_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
