# Generated by Django 3.0.1 on 2021-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210108_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_Image',
            field=models.ImageField(default='images/default_profile/default-profile.jpg', null=True, upload_to='images/'),
        ),
    ]
