# Generated by Django 3.0.1 on 2021-01-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_Image',
            field=models.ImageField(default='images/default_profile/default-profile.jpg', upload_to='images/profile_pic/'),
        ),
    ]
