# Generated by Django 3.0.1 on 2021-01-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
