# Generated by Django 3.0.1 on 2021-01-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210113_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chategory',
            new_name='Category',
        ),
    ]
